[package]
name = "rs_novel"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
serde = "1.0.99"
serde_json = "1.0.99"

[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3